/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Celular;
import db.DBCelular;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.LogicaCelular;
import logica.LogicaRecargas;
import modelo.Recargas;

/**
 *
 * @author emili
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNumeroCelular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoEstadoCelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoValorRecarga = new javax.swing.JTextField();
        botonInsertarCelular = new javax.swing.JButton();
        botonpagarRecarga = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        campoNumeroCelular2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingresar Nuevo Celular");

        jLabel2.setText("Numero Celular");

        jLabel3.setText("Estado(0: inhabilitado, 1: habilitado)");

        jLabel5.setText("Recargar Celular");

        jLabel6.setText("Valor(en $):");

        campoValorRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorRecargaActionPerformed(evt);
            }
        });

        botonInsertarCelular.setText("INSERTAR");
        botonInsertarCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarCelularActionPerformed(evt);
            }
        });

        botonpagarRecarga.setText("PAGAR");
        botonpagarRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpagarRecargaActionPerformed(evt);
            }
        });

        jLabel4.setText("Planes desde $1 por 5gb");

        jLabel7.setText("Numero Celular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonpagarRecarga)
                                .addGap(120, 120, 120))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(90, 90, 90))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonInsertarCelular)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNumeroCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoEstadoCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoValorRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNumeroCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(campoNumeroCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(campoValorRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(botonpagarRecarga))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(campoNumeroCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(campoEstadoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(botonInsertarCelular)))
                .addContainerGap(396, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonpagarRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpagarRecargaActionPerformed

        Celular objCelular = new Celular();
        LogicaCelular objLogicaCelular = new LogicaCelular();
        Recargas objRecargas = new Recargas();
        LogicaRecargas objLogicaRecargas = new LogicaRecargas();

        try {
            // 1. Obtener datos de la interfaz
            String numeroCelular = campoNumeroCelular2.getText().trim();
            String valorRecargaStr = campoValorRecarga.getText().trim();

            // 2. Validar campos vacíos
            if (numeroCelular.isEmpty() || valorRecargaStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
                return;
            }

            // 3. Convertir valor a entero
            int valorRecarga = Integer.parseInt(valorRecargaStr);

            // 4. Validar valor positivo
            if (valorRecarga <= 0) {
                JOptionPane.showMessageDialog(this, "El valor debe ser mayor a 0");
                return;
            }

            // 5. Ejecutar lógica de recarga
            LogicaRecargas logica = new LogicaRecargas();
            String resultado = logica.realizarRecarga(numeroCelular, valorRecarga);

            // 6. Mostrar resultado
            JOptionPane.showMessageDialog(this, resultado);

            // 7. Limpiar campos
            campoNumeroCelular2.setText("");
            campoValorRecarga.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor debe ser un número entero");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_botonpagarRecargaActionPerformed

    private void campoValorRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorRecargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorRecargaActionPerformed

    private void botonInsertarCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarCelularActionPerformed
        Celular objCelular = new Celular();
        LogicaCelular objLogicaCelular = new LogicaCelular();

        // Obtener los datos ingresados
        String numeroCelular = campoNumeroCelular.getText();
        String estadoCelular = campoEstadoCelular.getText();

        // Cargar el objeto Profesor
        objCelular.setNumero(numeroCelular);
        objCelular.setEstado(Integer.valueOf(estadoCelular));

        // REALIZAR INSERCION
        try {
            // Insertar profesor
            objLogicaCelular.Insertar(objCelular);

            // Mostrar mensaje
            JOptionPane.showMessageDialog(this, "CELULAR INGRESADO CON EXITO");

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "ERROR EN LA INSERCION: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botonInsertarCelularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInsertarCelular;
    private javax.swing.JButton botonpagarRecarga;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField campoEstadoCelular;
    private javax.swing.JTextField campoNumeroCelular;
    private javax.swing.JTextField campoNumeroCelular2;
    private javax.swing.JTextField campoValorRecarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
